export const FULL_ITEM_LIST = [
  "Onions",
  "Potatoes",
  "Tomatoes",
  "Ginger",
  "Garlic",
  "Green Chilies",
  "Coriander Leaves",
  "Mint Leaves",
  "Curry Leaves",
  "Cabbage",
  "Lettuce",
  "Capsicum",
  "Cucumber",
  "Carrots",
  "Cauliflower",
  "Green Peas",
  "Lemons",
  "Tamarind",
  "Raw Mangoes",
  "Maida",
  "Besan",
  "Atta",
  "Sooji",
  "Rice Flour",
  "Rice",
  "Muri",
  "Poha",
  "Chana",
  "White Peas",
  "Various Lentils",
  "Paneer",
  "Cheese",
  "Dahi",
  "Milk",
  "Chicken",
  "Mutton",
  "Eggs",
  "Soya Chunks",
  "Turmeric Powder",
  "Red Chili Powder",
  "Coriander Powder",
  "Cumin Powder",
  "Garam Masala",
  "Chaat Masala",
  "Iodized Salt",
  "Black Salt",
  "Cumin Seeds",
  "Mustard Seeds",
  "Cloves",
  "Cinnamon",
  "Cardamom",
  "Black Peppercorns",
  "Asafoetida",
  "Vegetable Oil",
  "Mustard Oil",
  "Palm Oil",
  "Butter",
  "Ghee",
  "Margarine",
  "Ginger-Garlic Paste",
  "Tomato Ketchup",
  "Soy Sauce",
  "Chili Sauce",
  "Vinegar",
  "Mustard Sauce",
  "Tamarind Paste",
  "Mint-Coriander Chutney",
  "Bread Slices",
  "Pav & Burger Buns",
  "Noodles",
  "Papad",
  "Sev",
  "Ready-made Puris",
  "Tea Leaves",
  "Coffee Powder",
  "Sugar",
  "Ice",
]

export const BOT_SUPPLIERS = [
  {
    id: "supplier_1",
    name: "Mumbai Fresh Mart",
    avatar: "🏪",
    strategy: "aggressive",
    base_prices: {
      Onions: 25,
      Potatoes: 30,
      Tomatoes: 40,
      Milk: 55,
      Eggs: 6,
      Chicken: 180,
      Rice: 45,
      Dahi: 60,
      Paneer: 300,
      Butter: 450,
    },
    bulk_tiers: [
      { min_qty: 10, discount: 0.05 },
      { min_qty: 50, discount: 0.12 },
      { min_qty: 100, discount: 0.18 },
    ],
    quality_score: 8.5,
    delivery_radius: 15,
    min_order_qty: 500,
    location: [10, 10] as [number, number],
    reliability_score: 8.5,
  },
  {
    id: "supplier_2",
    name: "Wholesale Kings",
    avatar: "👑",
    strategy: "conservative",
    base_prices: {
      Onions: 22,
      Potatoes: 28,
      Tomatoes: 38,
      Milk: 52,
      Eggs: 5.5,
      Chicken: 175,
      Rice: 42,
      Dahi: 55,
      Paneer: 280,
      Butter: 420,
    },
    bulk_tiers: [
      { min_qty: 20, discount: 0.08 },
      { min_qty: 75, discount: 0.15 },
      { min_qty: 150, discount: 0.22 },
    ],
    quality_score: 9.0,
    delivery_radius: 20,
    min_order_qty: 800,
    location: [8, 12] as [number, number],
    reliability_score: 9.0,
  },
  {
    id: "supplier_3",
    name: "Quick Supply Co",
    avatar: "🚚",
    strategy: "reactive",
    base_prices: {
      Onions: 27,
      Potatoes: 32,
      Tomatoes: 42,
      Milk: 58,
      Eggs: 6.2,
      Chicken: 185,
      Rice: 48,
      Dahi: 65,
      Paneer: 320,
      Butter: 480,
    },
    bulk_tiers: [
      { min_qty: 15, discount: 0.06 },
      { min_qty: 60, discount: 0.13 },
      { min_qty: 120, discount: 0.2 },
    ],
    quality_score: 8.2,
    delivery_radius: 12,
    min_order_qty: 400,
    location: [12, 8] as [number, number],
    reliability_score: 8.2,
  },
  {
    id: "supplier_4",
    name: "Premium Vendors Ltd",
    avatar: "⭐",
    strategy: "sniper",
    base_prices: {
      Onions: 24,
      Potatoes: 29,
      Tomatoes: 39,
      Milk: 54,
      Eggs: 5.8,
      Chicken: 178,
      Rice: 44,
      Dahi: 58,
      Paneer: 290,
      Butter: 440,
    },
    bulk_tiers: [
      { min_qty: 25, discount: 0.07 },
      { min_qty: 80, discount: 0.14 },
      { min_qty: 160, discount: 0.21 },
    ],
    quality_score: 9.2,
    delivery_radius: 18,
    min_order_qty: 600,
    location: [9, 11] as [number, number],
    reliability_score: 9.2,
  },
  {
    id: "supplier_5",
    name: "Local Market Hub",
    avatar: "🏬",
    strategy: "frequent",
    base_prices: {
      Onions: 26,
      Potatoes: 31,
      Tomatoes: 41,
      Milk: 56,
      Eggs: 6.0,
      Chicken: 182,
      Rice: 46,
      Dahi: 62,
      Paneer: 310,
      Butter: 460,
    },
    bulk_tiers: [
      { min_qty: 12, discount: 0.04 },
      { min_qty: 40, discount: 0.1 },
      { min_qty: 90, discount: 0.16 },
    ],
    quality_score: 8.7,
    delivery_radius: 14,
    min_order_qty: 450,
    location: [11, 9] as [number, number],
    reliability_score: 8.7,
  },
]

export const SAMPLE_ORDERS = [
  {
    name: "Restaurant Daily Order",
    items: { Onions: 50, Tomatoes: 30, Chicken: 25, Rice: 40, Eggs: 100 },
    location: [10, 10] as [number, number],
  },
  {
    name: "Grocery Store Restock",
    items: { Milk: 80, Dahi: 60, Paneer: 20, Butter: 15, Eggs: 200 },
    location: [11, 9] as [number, number],
  },
  {
    name: "Catering Service Order",
    items: { Potatoes: 100, Onions: 80, Tomatoes: 60, Chicken: 50, Rice: 80 },
    location: [9, 11] as [number, number],
  },
]
